name: ASP.NET Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Soy un paso que no hace nada
        run: echo "¡Hola bueys!"

      - name: Soy otro paso innecesario
        run: whoami
      - name: Otro más, por si dos no fueran necesario
        run: pwd
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restaurar paquetes
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar Tests
        run: dotnet test --configuration Release --no-build --verbosity normal
